using System;
using System.Reflection;
using System.Runtime.InteropServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("0.0.1.0")]
[assembly: AssemblyTitleAttribute("OpenTK-Tetris")]
[assembly: AssemblyDescriptionAttribute("Yet another tetris implementation")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2012  Joseph Dillon")]

